/**
 * 运营商图标 catalog - 自动生成
 * 生成时间: 2026-08-03T17:59:47.200Z
 * 覆盖 140 个 MCC，共 500 个运营商
 */

export const ICON_CATALOG: Record<string, { mnc: string; icon: string; scope: string }[]> = {
  '202': [
    { mnc: '01', icon: 'cosmote', scope: '202' },
    { mnc: '05', icon: 'vodafone', scope: 'worldwide' },
  ],
  '204': [
    { mnc: '04', icon: 'vodafone', scope: 'worldwide' },
    { mnc: '07', icon: 'teleena', scope: '204' },
    { mnc: '08', icon: 'kpn', scope: '204' },
    { mnc: '09', icon: 'lycamobile', scope: 'worldwide' },
    { mnc: '16', icon: 'odido', scope: '204' },
  ],
  '206': [
    { mnc: '01', icon: 'proximus', scope: '206' },
    { mnc: '10', icon: 'orange', scope: 'worldwide' },
    { mnc: '12', icon: 'meo', scope: 'worldwide' },
    { mnc: '20', icon: 'base', scope: '206' },
    { mnc: '28', icon: 'bics', scope: '206' },
  ],
  '208': [
    { mnc: '01', icon: 'orange-france', scope: 'worldwide' },
    { mnc: '09', icon: 'sfr', scope: '208' },
    { mnc: '10', icon: 'sfr', scope: '208' },
    { mnc: '15', icon: 'iliad', scope: '208' },
    { mnc: '20', icon: 'bouygues', scope: '208' },
    { mnc: '25', icon: 'lycamobile', scope: 'worldwide' },
    { mnc: '38', icon: 'lebara', scope: 'worldwide' },
  ],
  '213': [
    { mnc: '03', icon: 'mobiland', scope: '213' },
  ],
  '214': [
    { mnc: '01', icon: 'vodafone', scope: 'worldwide' },
    { mnc: '03', icon: 'orange', scope: 'worldwide' },
    { mnc: '04', icon: 'yoigo', scope: '214' },
    { mnc: '05', icon: 'movistar', scope: 'worldwide' },
    { mnc: '06', icon: 'vodafone', scope: 'worldwide' },
    { mnc: '07', icon: 'movistar', scope: 'worldwide' },
    { mnc: '22', icon: 'meo', scope: 'worldwide' },
    { mnc: '34', icon: 'aire', scope: '214' },
  ],
  '216': [
    { mnc: '01', icon: 'telenor', scope: 'worldwide' },
    { mnc: '30', icon: 't-mobile', scope: 'worldwide' },
    { mnc: '70', icon: 'vodafone', scope: 'worldwide' },
  ],
  '218': [
    { mnc: '03', icon: 'ht-eronet', scope: '218' },
    { mnc: '05', icon: 'novotel', scope: '218' },
    { mnc: '90', icon: 'bh-mobile', scope: '218' },
  ],
  '219': [
    { mnc: '01', icon: 't-mobile', scope: 'worldwide' },
    { mnc: '02', icon: 'tele2', scope: 'worldwide' },
    { mnc: '10', icon: 'one', scope: 'worldwide' },
  ],
  '220': [
    { mnc: '01', icon: 'telenor', scope: 'worldwide' },
    { mnc: '03', icon: 'mts', scope: '220' },
    { mnc: '05', icon: 'one', scope: 'worldwide' },
  ],
  '222': [
    { mnc: '01', icon: 'tim', scope: '222' },
    { mnc: '08', icon: 'fastweb', scope: '222' },
    { mnc: '10', icon: 'vodafone', scope: 'worldwide' },
    { mnc: '35', icon: 'lycamobile', scope: 'worldwide' },
    { mnc: '49', icon: 'vianova', scope: '222' },
    { mnc: '50', icon: 'iliad', scope: '222' },
    { mnc: '53', icon: 'coop-voce', scope: '222' },
    { mnc: '56', icon: 'spusu', scope: 'worldwide' },
    { mnc: '88', icon: 'wind', scope: '222' },
  ],
  '226': [
    { mnc: '01', icon: 'vodafone', scope: 'worldwide' },
    { mnc: '05', icon: 'meo', scope: 'worldwide' },
    { mnc: '10', icon: 'orange', scope: 'worldwide' },
  ],
  '228': [
    { mnc: '01', icon: 'swisscom', scope: '228' },
    { mnc: '02', icon: 'sunrise', scope: '228' },
    { mnc: '03', icon: 'salt', scope: '228' },
    { mnc: '54', icon: 'lycamobile', scope: 'worldwide' },
    { mnc: '58', icon: 'beeone', scope: '228' },
    { mnc: '71', icon: 'spusu-international', scope: 'worldwide' },
  ],
  '230': [
    { mnc: '01', icon: 't-mobile', scope: 'worldwide' },
    { mnc: '02', icon: 'o2', scope: 'worldwide' },
    { mnc: '03', icon: 'vodafone', scope: 'worldwide' },
  ],
  '231': [
    { mnc: '01', icon: 'orange', scope: 'worldwide' },
    { mnc: '02', icon: 't-mobile', scope: 'worldwide' },
    { mnc: '03', icon: '4ka', scope: '231' },
    { mnc: '06', icon: 'o2', scope: 'worldwide' },
  ],
  '232': [
    { mnc: '01', icon: 'one', scope: 'worldwide' },
    { mnc: '03', icon: 't-mobile', scope: 'worldwide' },
    { mnc: '05', icon: '3', scope: '232' },
    { mnc: '07', icon: 't-mobile', scope: 'worldwide' },
    { mnc: '08', icon: 'lycamobile', scope: 'worldwide' },
    { mnc: '10', icon: '3', scope: '232' },
    { mnc: '11', icon: 'bob', scope: '232' },
    { mnc: '12', icon: 'one', scope: 'worldwide' },
    { mnc: '17', icon: 'spusu', scope: 'worldwide' },
    { mnc: '20', icon: 'm-tel', scope: '232' },
  ],
  '234': [
    { mnc: '03', icon: 'airtel', scope: '234' },
    { mnc: '10', icon: 'o2', scope: '234' },
    { mnc: '15', icon: 'vodafone', scope: 'worldwide' },
    { mnc: '18', icon: 'cloud-9-mobile', scope: '234' },
    { mnc: '20', icon: '3', scope: '234' },
    { mnc: '25', icon: 'truphone', scope: '234' },
    { mnc: '26', icon: 'lycamobile', scope: 'worldwide' },
    { mnc: '30', icon: 'orange', scope: '234' },
    { mnc: '33', icon: 'orange', scope: '234' },
    { mnc: '40', icon: 'spusu-international', scope: 'worldwide' },
    { mnc: '50', icon: 'jt', scope: '234' },
    { mnc: '55', icon: 'airtel', scope: '234' },
    { mnc: '57', icon: 'sky', scope: 'worldwide' },
    { mnc: '58', icon: 'pronto-gsm', scope: '234' },
    { mnc: '87', icon: 'lebara', scope: 'worldwide' },
  ],
  '238': [
    { mnc: '02', icon: 'telenor-nordic', scope: 'worldwide' },
    { mnc: '06', icon: '3', scope: '238' },
    { mnc: '12', icon: 'lycamobile', scope: 'worldwide' },
  ],
  '240': [
    { mnc: '02', icon: '3', scope: '240' },
    { mnc: '07', icon: 'tele2', scope: 'worldwide' },
    { mnc: '08', icon: 'telenor-nordic', scope: 'worldwide' },
    { mnc: '12', icon: 'lycamobile', scope: 'worldwide' },
  ],
  '242': [
    { mnc: '02', icon: 'telia', scope: 'worldwide' },
    { mnc: '05', icon: 'telia', scope: 'worldwide' },
    { mnc: '14', icon: 'ice', scope: '242' },
    { mnc: '23', icon: 'lycamobile', scope: 'worldwide' },
  ],
  '244': [
    { mnc: '05', icon: 'elisa', scope: '244' },
    { mnc: '91', icon: 'telia', scope: 'worldwide' },
  ],
  '246': [
    { mnc: '02', icon: 'bit', scope: 'worldwide' },
    { mnc: '03', icon: 'tele2', scope: 'worldwide' },
  ],
  '247': [
    { mnc: '01', icon: 'lmt', scope: '247' },
    { mnc: '02', icon: 'tele2', scope: 'worldwide' },
    { mnc: '05', icon: 'bit', scope: 'worldwide' },
  ],
  '248': [
    { mnc: '01', icon: 'telia', scope: '248' },
    { mnc: '02', icon: 'elisa', scope: '248' },
  ],
  '250': [
    { mnc: '01', icon: 'mts', scope: '250' },
    { mnc: '02', icon: 'megafon', scope: 'worldwide' },
    { mnc: '11', icon: 'yota', scope: '250' },
    { mnc: '19', icon: 'indigo', scope: '250' },
    { mnc: '20', icon: 'tele2', scope: '250' },
    { mnc: '26', icon: 'vtb', scope: '250' },
    { mnc: '32', icon: 'k-telecom', scope: '250' },
    { mnc: '45', icon: 'gpb-mobile', scope: '250' },
    { mnc: '47', icon: 'next-mobile', scope: '250' },
    { mnc: '50', icon: 'bezlimitnoru', scope: '250' },
    { mnc: '54', icon: 'ttk', scope: '250' },
    { mnc: '57', icon: 'matrix', scope: '250' },
    { mnc: '60', icon: 'ktk-telecom', scope: '250' },
    { mnc: '62', icon: 'tinkoff-mobile', scope: '250' },
    { mnc: '94', icon: 'mirtelecom', scope: '250' },
    { mnc: '96', icon: 'plus-7telecom', scope: '250' },
    { mnc: '98', icon: 'mcs', scope: '250' },
    { mnc: '99', icon: 'beeline', scope: 'worldwide' },
  ],
  '255': [
    { mnc: '01', icon: 'vodafone', scope: 'worldwide' },
    { mnc: '03', icon: 'kyivstar', scope: '255' },
    { mnc: '06', icon: 'lifecell', scope: '255' },
    { mnc: '07', icon: '3mob', scope: '255' },
  ],
  '257': [
    { mnc: '01', icon: 'one', scope: 'worldwide' },
    { mnc: '02', icon: 'mts', scope: '257' },
    { mnc: '04', icon: 'life', scope: '257' },
  ],
  '259': [
    { mnc: '01', icon: 'orange', scope: 'worldwide' },
    { mnc: '05', icon: 'unit', scope: '259' },
  ],
  '260': [
    { mnc: '01', icon: 'plus', scope: '260' },
    { mnc: '02', icon: 't-mobile', scope: 'worldwide' },
    { mnc: '03', icon: 'orange-france', scope: 'worldwide' },
    { mnc: '06', icon: 'play', scope: '260' },
    { mnc: '09', icon: 'lycamobile', scope: 'worldwide' },
  ],
  '262': [
    { mnc: '01', icon: 'telekom', scope: '262' },
    { mnc: '02', icon: 'vodafone', scope: 'worldwide' },
    { mnc: '03', icon: 'o2', scope: '262' },
    { mnc: '07', icon: 'o2', scope: '262' },
    { mnc: '14', icon: 'lebara', scope: 'worldwide' },
    { mnc: '23', icon: 'gmx', scope: '262' },
    { mnc: '24', icon: 'esim-me', scope: '262' },
    { mnc: '43', icon: 'lycamobile', scope: 'worldwide' },
  ],
  '266': [
    { mnc: '01', icon: 'gibtel', scope: '266' },
  ],
  '268': [
    { mnc: '01', icon: 'vodafone', scope: 'worldwide' },
    { mnc: '02', icon: 'meo', scope: 'worldwide' },
    { mnc: '03', icon: 'nos', scope: '268' },
    { mnc: '04', icon: 'lycamobile', scope: 'worldwide' },
    { mnc: '06', icon: 'meo', scope: '268' },
  ],
  '270': [
    { mnc: '02', icon: 'mtx-connect', scope: '270' },
    { mnc: '99', icon: 'orange', scope: 'worldwide' },
  ],
  '272': [
    { mnc: '01', icon: 'vodafone', scope: 'worldwide' },
    { mnc: '02', icon: '3', scope: '272' },
    { mnc: '03', icon: 'eir', scope: '272' },
    { mnc: '13', icon: 'lycamobile', scope: 'worldwide' },
    { mnc: '25', icon: 'sky', scope: 'worldwide' },
  ],
  '274': [
    { mnc: '01', icon: 's-minn', scope: '274' },
    { mnc: '02', icon: 'vodafone', scope: '274' },
    { mnc: '11', icon: 'nova', scope: '274' },
  ],
  '276': [
    { mnc: '02', icon: 'vodafone', scope: 'worldwide' },
  ],
  '278': [
    { mnc: '01', icon: 'vodafone', scope: 'worldwide' },
    { mnc: '21', icon: 'go', scope: '278' },
    { mnc: '77', icon: 'melita', scope: '278' },
  ],
  '280': [
    { mnc: '01', icon: 'cytamobile-vodafone', scope: '280' },
    { mnc: '20', icon: 'primetel', scope: '280' },
  ],
  '282': [
    { mnc: '01', icon: 'geocell', scope: '282' },
    { mnc: '02', icon: 'magti', scope: '282' },
    { mnc: '04', icon: 'beeline', scope: '282' },
  ],
  '283': [
    { mnc: '01', icon: 'beeline', scope: '283' },
    { mnc: '05', icon: 'vivacell-mts', scope: '283' },
    { mnc: '10', icon: 'ucom', scope: '283' },
  ],
  '284': [
    { mnc: '01', icon: 'one', scope: 'worldwide' },
    { mnc: '03', icon: 'vivacom', scope: '284' },
    { mnc: '05', icon: 'telenor', scope: 'worldwide' },
  ],
  '286': [
    { mnc: '01', icon: 'turkcell', scope: '286' },
    { mnc: '02', icon: 'vodafone', scope: 'worldwide' },
    { mnc: '03', icon: 't-rk-telekom', scope: '286' },
  ],
  '288': [
    { mnc: '01', icon: 'faroese-telecom', scope: '288' },
  ],
  '289': [
    { mnc: '67', icon: 'aquafon', scope: '289' },
    { mnc: '88', icon: 'a-mobile', scope: '289' },
  ],
  '290': [
    { mnc: '01', icon: 'tusass', scope: '290' },
  ],
  '293': [
    { mnc: '40', icon: 'one', scope: 'worldwide' },
    { mnc: '41', icon: 'mobitel', scope: '293' },
  ],
  '294': [
    { mnc: '01', icon: 't-mobile', scope: 'worldwide' },
    { mnc: '03', icon: 'one', scope: 'worldwide' },
  ],
  '295': [
    { mnc: '05', icon: 'fl1', scope: '295' },
  ],
  '297': [
    { mnc: '01', icon: 'telenor', scope: '297' },
    { mnc: '02', icon: 't-mobile', scope: 'worldwide' },
    { mnc: '03', icon: 'mtel-cg', scope: '297' },
  ],
  '302': [
    { mnc: '220', icon: 'telus-mobility', scope: '302' },
    { mnc: '370', icon: 'fido', scope: '302' },
    { mnc: '490', icon: 'freedom-mobile', scope: '302' },
    { mnc: '500', icon: 'videotron', scope: '302' },
    { mnc: '610', icon: 'bell-mobility', scope: '302' },
    { mnc: '720', icon: 'rogers-wireless', scope: '302' },
  ],
  '310': [
    { mnc: '020', icon: 'union-wireless', scope: '310' },
    { mnc: '84', icon: 'telna-mobile', scope: '310' },
    { mnc: '140', icon: 'gta-wireless', scope: '310' },
    { mnc: '150', icon: 'at-and-t', scope: '310' },
    { mnc: '240', icon: 't-mobile', scope: 'worldwide' },
    { mnc: '260', icon: 't-mobile', scope: 'worldwide' },
    { mnc: '280', icon: 'at-and-t', scope: '310' },
    { mnc: '380', icon: 'at-and-t', scope: '310' },
    { mnc: '410', icon: 'at-and-t', scope: '310' },
    { mnc: '840', icon: 'telna-mobile', scope: '310' },
  ],
  '311': [
    { mnc: '23', icon: 'c-spire', scope: '311' },
    { mnc: '210', icon: 'telnyx', scope: '311' },
    { mnc: '580', icon: 'u-s-cellular', scope: '311' },
  ],
  '312': [
    { mnc: '420', icon: 'nex-tech-wireless', scope: '312' },
  ],
  '313': [
    { mnc: '460', icon: 'mobi', scope: '313' },
    { mnc: '790', icon: 'liberty-pr', scope: '313' },
  ],
  '334': [
    { mnc: '020', icon: 'telcel', scope: '334' },
    { mnc: '030', icon: 'movistar', scope: '334' },
    { mnc: '050', icon: 'at-and-t', scope: '334' },
    { mnc: '130', icon: 'axtel', scope: '334' },
    { mnc: '140', icon: 'altan-redes', scope: '334' },
  ],
  '338': [
    { mnc: '05', icon: 'digicel', scope: 'worldwide' },
    { mnc: '050', icon: 'digicel', scope: 'worldwide' },
  ],
  '362': [
    { mnc: '91', icon: 'flow', scope: '362' },
  ],
  '363': [
    { mnc: '01', icon: 'setar', scope: '363' },
  ],
  '364': [
    { mnc: '39', icon: 'btc', scope: '364' },
  ],
  '370': [
    { mnc: '02', icon: 'claro', scope: 'worldwide' },
  ],
  '374': [
    { mnc: '130', icon: 'digicel', scope: 'worldwide' },
  ],
  '400': [
    { mnc: '01', icon: 'azercell', scope: '400' },
    { mnc: '02', icon: 'bakcell', scope: '400' },
    { mnc: '04', icon: 'azerfon', scope: '400' },
  ],
  '401': [
    { mnc: '01', icon: 'beeline', scope: 'worldwide' },
    { mnc: '02', icon: 'kcell', scope: '401' },
    { mnc: '77', icon: 'tele2', scope: 'worldwide' },
  ],
  '404': [
    { mnc: '07', icon: 'vi', scope: 'worldwide' },
    { mnc: '13', icon: 'vodafone', scope: 'worldwide' },
    { mnc: '15', icon: 'vodafone', scope: 'worldwide' },
    { mnc: '19', icon: 'vi', scope: 'worldwide' },
    { mnc: '22', icon: 'vi', scope: 'worldwide' },
    { mnc: '27', icon: 'vodafone', scope: 'worldwide' },
    { mnc: '40', icon: 'airtel', scope: 'worldwide' },
    { mnc: '43', icon: 'vodafone', scope: 'worldwide' },
    { mnc: '45', icon: 'airtel', scope: 'worldwide' },
    { mnc: '46', icon: 'vodafone', scope: 'worldwide' },
    { mnc: '49', icon: 'airtel', scope: 'worldwide' },
    { mnc: '60', icon: 'vodafone', scope: 'worldwide' },
    { mnc: '70', icon: 'airtel', scope: 'worldwide' },
    { mnc: '78', icon: 'vi', scope: 'worldwide' },
    { mnc: '86', icon: 'vodafone', scope: 'worldwide' },
    { mnc: '87', icon: 'vi', scope: 'worldwide' },
    { mnc: '89', icon: 'vi', scope: 'worldwide' },
    { mnc: '90', icon: 'airtel', scope: 'worldwide' },
    { mnc: '92', icon: 'airtel', scope: 'worldwide' },
    { mnc: '93', icon: 'airtel', scope: 'worldwide' },
    { mnc: '97', icon: 'airtel', scope: 'worldwide' },
  ],
  '405': [
    { mnc: '51', icon: 'airtel', scope: 'worldwide' },
    { mnc: '52', icon: 'airtel', scope: 'worldwide' },
    { mnc: '54', icon: 'airtel', scope: 'worldwide' },
    { mnc: '67', icon: 'vodafone', scope: 'worldwide' },
    { mnc: '75', icon: 'vi', scope: 'worldwide' },
    { mnc: '702', icon: 'vi', scope: 'worldwide' },
    { mnc: '840', icon: 'jio', scope: '405' },
    { mnc: '848', icon: 'vi', scope: 'worldwide' },
    { mnc: '852', icon: 'vi', scope: 'worldwide' },
    { mnc: '853', icon: 'vi', scope: 'worldwide' },
    { mnc: '854', icon: 'jio', scope: '405' },
    { mnc: '856', icon: 'jio', scope: '405' },
    { mnc: '857', icon: 'jio', scope: '405' },
    { mnc: '861', icon: 'jio', scope: '405' },
    { mnc: '862', icon: 'jio', scope: '405' },
    { mnc: '863', icon: 'jio', scope: '405' },
    { mnc: '864', icon: 'jio', scope: '405' },
    { mnc: '866', icon: 'jio', scope: '405' },
    { mnc: '868', icon: 'jio', scope: '405' },
    { mnc: '869', icon: 'jio', scope: '405' },
    { mnc: '870', icon: 'jio', scope: '405' },
    { mnc: '873', icon: 'jio', scope: '405' },
  ],
  '410': [
    { mnc: '01', icon: 'jazz', scope: '410' },
    { mnc: '03', icon: 'ufone', scope: '410' },
    { mnc: '04', icon: 'zong', scope: '410' },
  ],
  '413': [
    { mnc: '01', icon: 'mobitel', scope: '413' },
    { mnc: '02', icon: 'dialog', scope: '413' },
    { mnc: '08', icon: 'hutch', scope: '413' },
  ],
  '414': [
    { mnc: '01', icon: 'mpt', scope: '414' },
    { mnc: '05', icon: 'ooredoo', scope: '414' },
    { mnc: '06', icon: 'telenor', scope: '414' },
  ],
  '415': [
    { mnc: '03', icon: 'touch', scope: '415' },
  ],
  '416': [
    { mnc: '03', icon: 'umniah', scope: '416' },
  ],
  '417': [
    { mnc: '01', icon: 'syriatel', scope: '417' },
    { mnc: '02', icon: 'mtn', scope: 'worldwide' },
  ],
  '418': [
    { mnc: '20', icon: 'zain', scope: 'worldwide' },
  ],
  '419': [
    { mnc: '02', icon: 'zain', scope: 'worldwide' },
    { mnc: '03', icon: 'ooredoo', scope: 'worldwide' },
    { mnc: '04', icon: 'stc', scope: 'worldwide' },
  ],
  '420': [
    { mnc: '01', icon: 'stc', scope: 'worldwide' },
    { mnc: '03', icon: 'mobily', scope: '420' },
    { mnc: '04', icon: 'zain-sa', scope: '420' },
    { mnc: '05', icon: 'virgin-mobile', scope: '420' },
    { mnc: '06', icon: 'lebara', scope: 'worldwide' },
    { mnc: '09', icon: 'salammobile', scope: '420' },
    { mnc: '10', icon: 'redbullmobile', scope: '420' },
  ],
  '422': [
    { mnc: '02', icon: 'omantel', scope: '422' },
    { mnc: '03', icon: 'ooredoo', scope: 'worldwide' },
    { mnc: '06', icon: 'vodafone', scope: 'worldwide' },
  ],
  '424': [
    { mnc: '02', icon: 'etisalat', scope: 'worldwide' },
    { mnc: '03', icon: 'du', scope: '424' },
  ],
  '425': [
    { mnc: '01', icon: 'partner', scope: '425' },
    { mnc: '02', icon: 'cellcom', scope: '425' },
    { mnc: '03', icon: 'pelephone', scope: '425' },
    { mnc: '05', icon: 'jawwal', scope: '425' },
    { mnc: '06', icon: 'ooredoo', scope: 'worldwide' },
    { mnc: '07', icon: 'hot-mobile', scope: '425' },
    { mnc: '09', icon: 'we4g', scope: '425' },
    { mnc: '12', icon: 'free-telecom', scope: '425' },
    { mnc: '19', icon: '019-mobile', scope: '425' },
    { mnc: '21', icon: 'bezeq-international', scope: '425' },
    { mnc: '26', icon: 'annatel', scope: '425' },
  ],
  '426': [
    { mnc: '02', icon: 'zain', scope: 'worldwide' },
    { mnc: '04', icon: 'stc', scope: 'worldwide' },
  ],
  '427': [
    { mnc: '01', icon: 'ooredoo', scope: 'worldwide' },
    { mnc: '02', icon: 'vodafone', scope: 'worldwide' },
  ],
  '428': [
    { mnc: '06', icon: 'gmobile-4g', scope: '428' },
    { mnc: '33', icon: 'ondo', scope: '428' },
    { mnc: '88', icon: 'unitel', scope: '428' },
    { mnc: '99', icon: 'mobicom', scope: '428' },
  ],
  '429': [
    { mnc: '01', icon: 'nepal-telecom-ndcl', scope: '429' },
  ],
  '434': [
    { mnc: '04', icon: 'beeline', scope: 'worldwide' },
    { mnc: '05', icon: 'ucell', scope: '434' },
    { mnc: '08', icon: 'uzmobile', scope: '434' },
    { mnc: '10', icon: 'humans', scope: '434' },
  ],
  '436': [
    { mnc: '02', icon: 'tcell', scope: '436' },
    { mnc: '03', icon: 'megafon', scope: 'worldwide' },
  ],
  '437': [
    { mnc: '01', icon: 'beeline', scope: 'worldwide' },
    { mnc: '05', icon: 'megacom', scope: '437' },
    { mnc: '09', icon: 'o', scope: '437' },
  ],
  '440': [
    { mnc: '03', icon: 'iijmio', scope: '440' },
    { mnc: '09', icon: 'marubeni', scope: '440' },
    { mnc: '10', icon: 'ntt-docomo', scope: '440' },
    { mnc: '11', icon: 'rakuten', scope: '440' },
    { mnc: '20', icon: 'softbank', scope: '440' },
    { mnc: '51', icon: 'au', scope: '440' },
    { mnc: '54', icon: 'au', scope: '440' },
  ],
  '450': [
    { mnc: '05', icon: 'sktelecom', scope: '450' },
    { mnc: '06', icon: 'lg-u-plus', scope: '450' },
    { mnc: '08', icon: 'kt', scope: '450' },
  ],
  '452': [
    { mnc: '01', icon: 'mobifone', scope: '452' },
    { mnc: '02', icon: 'vinaphone', scope: '452' },
    { mnc: '04', icon: 'viettel-mobile', scope: '452' },
    { mnc: '05', icon: 'vietnamobile', scope: '452' },
    { mnc: '08', icon: 'i-telecom', scope: '452' },
    { mnc: '09', icon: 'wintel', scope: '452' },
  ],
  '454': [
    { mnc: '00', icon: 'csl', scope: '454' },
    { mnc: '03', icon: '3', scope: '454' },
    { mnc: '06', icon: 'smartone', scope: '454' },
    { mnc: '07', icon: 'china-unicom', scope: '454' },
    { mnc: '12', icon: 'cmcc-hk', scope: '454' },
    { mnc: '19', icon: 'csl', scope: '454' },
    { mnc: '31', icon: 'ctexcel', scope: '454' },
    { mnc: '35', icon: 'webbing', scope: 'worldwide' },
  ],
  '455': [
    { mnc: '01', icon: 'ctm', scope: '455' },
    { mnc: '07', icon: 'china-telecom', scope: '455' },
  ],
  '456': [
    { mnc: '01', icon: 'cellcard', scope: '456' },
    { mnc: '06', icon: 'smart', scope: '456' },
    { mnc: '08', icon: 'metfone', scope: '456' },
  ],
  '457': [
    { mnc: '01', icon: 'laotel', scope: '457' },
    { mnc: '03', icon: 'unitel', scope: '457' },
    { mnc: '07', icon: 'best', scope: '457' },
    { mnc: '08', icon: 'beeline', scope: '457' },
  ],
  '460': [
    { mnc: '00', icon: 'china-mobile', scope: '460' },
    { mnc: '01', icon: 'china-unicom', scope: '460' },
    { mnc: '02', icon: 'china-mobile', scope: '460' },
    { mnc: '03', icon: 'china-telecom', scope: '460' },
    { mnc: '09', icon: 'china-unicom', scope: '460' },
    { mnc: '11', icon: 'china-telecom', scope: '460' },
  ],
  '466': [
    { mnc: '01', icon: 'fareastone', scope: '466' },
    { mnc: '05', icon: 'aptg', scope: '466' },
    { mnc: '89', icon: 't-star', scope: '466' },
    { mnc: '92', icon: 'chunghwa', scope: '466' },
    { mnc: '93', icon: 'mobitai', scope: '466' },
    { mnc: '97', icon: 'mobitai', scope: '466' },
  ],
  '467': [
    { mnc: '06', icon: 'koryolink', scope: '467' },
  ],
  '470': [
    { mnc: '01', icon: 'grameenphone', scope: '470' },
    { mnc: '02', icon: 'robi', scope: '470' },
    { mnc: '03', icon: 'banglalink', scope: '470' },
    { mnc: '04', icon: 'teletalk', scope: '470' },
    { mnc: '07', icon: 'airtel', scope: 'worldwide' },
  ],
  '472': [
    { mnc: '01', icon: 'dhiraagu', scope: '472' },
    { mnc: '02', icon: 'ooredoo', scope: 'worldwide' },
  ],
  '502': [
    { mnc: '12', icon: 'maxis', scope: '502' },
    { mnc: '16', icon: 'digi', scope: '502' },
    { mnc: '18', icon: 'u-mobile', scope: '502' },
    { mnc: '19', icon: 'celcom', scope: '502' },
    { mnc: '152', icon: 'yes', scope: '502' },
    { mnc: '153', icon: 'unifi', scope: '502' },
  ],
  '505': [
    { mnc: '01', icon: 'telstra', scope: '505' },
    { mnc: '02', icon: 'singtel', scope: '505' },
    { mnc: '03', icon: 'vodafone', scope: 'worldwide' },
  ],
  '510': [
    { mnc: '01', icon: '3', scope: '510' },
    { mnc: '09', icon: 'smartfren', scope: '510' },
    { mnc: '10', icon: 'telkomsel', scope: '510' },
    { mnc: '11', icon: 'xl', scope: '510' },
    { mnc: '89', icon: '3', scope: '510' },
  ],
  '515': [
    { mnc: '02', icon: 'globe', scope: '515' },
    { mnc: '03', icon: 'smart', scope: '515' },
    { mnc: '66', icon: 'dito', scope: '515' },
  ],
  '520': [
    { mnc: '03', icon: 'ais', scope: '520' },
    { mnc: '04', icon: 'true', scope: '520' },
    { mnc: '05', icon: 'dtac', scope: '520' },
  ],
  '525': [
    { mnc: '01', icon: 'singtel', scope: '525' },
    { mnc: '03', icon: 'm1', scope: '525' },
    { mnc: '05', icon: 'starhub', scope: '525' },
    { mnc: '10', icon: 'simba', scope: '525' },
  ],
  '528': [
    { mnc: '02', icon: 'pcsb', scope: '528' },
  ],
  '530': [
    { mnc: '01', icon: 'vodafone', scope: '530' },
    { mnc: '05', icon: 'spark', scope: '530' },
    { mnc: '24', icon: '2degrees', scope: '530' },
  ],
  '547': [
    { mnc: '20', icon: 'vini', scope: '547' },
  ],
  '549': [
    { mnc: '00', icon: 'digicel', scope: '549' },
  ],
  '552': [
    { mnc: '99', icon: 'pmci', scope: '552' },
  ],
  '602': [
    { mnc: '01', icon: 'orange', scope: 'worldwide' },
    { mnc: '02', icon: 'vodafone', scope: 'worldwide' },
    { mnc: '03', icon: 'etisalat', scope: 'worldwide' },
    { mnc: '04', icon: 'we', scope: '602' },
  ],
  '604': [
    { mnc: '00', icon: 'orange', scope: 'worldwide' },
    { mnc: '01', icon: 'iam', scope: '604' },
    { mnc: '02', icon: 'inwi', scope: '604' },
  ],
  '607': [
    { mnc: '03', icon: 'comium', scope: '607' },
  ],
  '617': [
    { mnc: '01', icon: 'my-t', scope: '617' },
    { mnc: '10', icon: 'emtel', scope: '617' },
  ],
  '621': [
    { mnc: '20', icon: 'airtel', scope: 'worldwide' },
    { mnc: '30', icon: 'mtn', scope: 'worldwide' },
    { mnc: '50', icon: 'glo', scope: '621' },
    { mnc: '74', icon: 'vitel', scope: '621' },
  ],
  '625': [
    { mnc: '02', icon: 't-plus', scope: '625' },
  ],
  '630': [
    { mnc: '90', icon: 'africell', scope: 'worldwide' },
  ],
  '631': [
    { mnc: '05', icon: 'africell', scope: 'worldwide' },
  ],
  '633': [
    { mnc: '10', icon: 'airtel', scope: 'worldwide' },
  ],
  '635': [
    { mnc: '10', icon: 'mtn', scope: 'worldwide' },
  ],
  '639': [
    { mnc: '02', icon: 'safaricom', scope: '639' },
    { mnc: '03', icon: 'airtel', scope: 'worldwide' },
    { mnc: '10', icon: 'faiba-4g', scope: '639' },
  ],
  '640': [
    { mnc: '02', icon: 'tigo', scope: '640' },
  ],
  '641': [
    { mnc: '01', icon: 'airtel', scope: 'worldwide' },
  ],
  '645': [
    { mnc: '01', icon: 'airtel', scope: 'worldwide' },
    { mnc: '02', icon: 'mtn', scope: 'worldwide' },
  ],
  '647': [
    { mnc: '03', icon: 'free', scope: '647' },
  ],
  '648': [
    { mnc: '04', icon: 'econet', scope: '648' },
  ],
  '654': [
    { mnc: '02', icon: 'telco-sa', scope: '654' },
  ],
  '655': [
    { mnc: '01', icon: 'vodafone', scope: 'worldwide' },
    { mnc: '02', icon: 'telkom', scope: '655' },
    { mnc: '07', icon: 'cell-c', scope: '655' },
    { mnc: '10', icon: 'mtn', scope: 'worldwide' },
  ],
  '702': [
    { mnc: '69', icon: 'smart', scope: '702' },
  ],
  '706': [
    { mnc: '03', icon: 'tigo', scope: '706' },
    { mnc: '04', icon: 'movistar', scope: 'worldwide' },
  ],
  '712': [
    { mnc: '01', icon: 'k-lbi-ice', scope: '712' },
    { mnc: '03', icon: 'claro', scope: 'worldwide' },
    { mnc: '04', icon: 'movistar', scope: 'worldwide' },
  ],
  '716': [
    { mnc: '15', icon: 'bitel', scope: '716' },
    { mnc: '20', icon: 'claro', scope: 'worldwide' },
  ],
  '722': [
    { mnc: '07', icon: 'movistar', scope: 'worldwide' },
    { mnc: '010', icon: 'movistar', scope: 'worldwide' },
    { mnc: '310', icon: 'claro', scope: 'worldwide' },
  ],
  '724': [
    { mnc: '02', icon: 'tim', scope: '724' },
    { mnc: '03', icon: 'tim', scope: '724' },
    { mnc: '04', icon: 'tim', scope: '724' },
    { mnc: '05', icon: 'claro', scope: 'worldwide' },
    { mnc: '10', icon: 'vivo', scope: '724' },
    { mnc: '11', icon: 'vivo', scope: '724' },
    { mnc: '17', icon: 'surf-telecom', scope: '724' },
    { mnc: '29', icon: 'unifique', scope: '724' },
    { mnc: '32', icon: 'algar-telecom', scope: '724' },
    { mnc: '33', icon: 'algar-telecom', scope: '724' },
    { mnc: '34', icon: 'algar-telecom', scope: '724' },
    { mnc: '77', icon: 'brisanet', scope: '724' },
  ],
  '730': [
    { mnc: '01', icon: 'entel', scope: '730' },
    { mnc: '02', icon: 'movistar', scope: 'worldwide' },
    { mnc: '07', icon: 'movistar', scope: 'worldwide' },
    { mnc: '09', icon: 'wom', scope: 'worldwide' },
  ],
  '732': [
    { mnc: '101', icon: 'claro', scope: 'worldwide' },
    { mnc: '111', icon: 'tigo', scope: 'worldwide' },
    { mnc: '123', icon: 'movistar', scope: 'worldwide' },
    { mnc: '154', icon: 'virgin-mobile', scope: '732' },
    { mnc: '187', icon: 'etb', scope: '732' },
    { mnc: '360', icon: 'wom', scope: 'worldwide' },
  ],
  '734': [
    { mnc: '02', icon: 'digicel', scope: 'worldwide' },
    { mnc: '06', icon: 'movilnet', scope: '734' },
  ],
  '736': [
    { mnc: '02', icon: 'entel', scope: '736' },
    { mnc: '03', icon: 'tigo', scope: 'worldwide' },
  ],
  '738': [
    { mnc: '002', icon: 'gt-and-t-cellink-plus', scope: '738' },
  ],
  '740': [
    { mnc: '00', icon: 'movistar', scope: 'worldwide' },
  ],
  '744': [
    { mnc: '02', icon: 'claro', scope: 'worldwide' },
    { mnc: '05', icon: 'personal', scope: '744' },
  ],
  '748': [
    { mnc: '01', icon: 'antel', scope: '748' },
    { mnc: '07', icon: 'movistar', scope: 'worldwide' },
  ],
  '901': [
    { mnc: '01', icon: 'webbing', scope: 'worldwide' },
    { mnc: '37', icon: 'transatel', scope: '901' },
    { mnc: '99', icon: 'roamless', scope: '901' },
  ],
}
